language: node_js
node_js:
- 9.11.1
# https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#travis-ci
cache:
  directories:
    - node_modules
# https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages
script: npm run deploy
deploy:
  # TEST
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    target_branch: master
    local_dir: build/
    on:
      branch: develop