language: node_js
node_js:
- 9.11.1
script: npm run build
deploy:
  # TEST
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    target_branch: master
    local_dir: build/
    on:
      branch: develop