// TODO: This list and the one in Clients.jsx have duplicate data
const casesList = [
	{
		client: 'Rabobank',
		path: 'rabobank',
		image: `/images/cases/stock-photo-utrecht-netherlands-april-rabobank-headquarters-building-rabobank-is-a-dutch-211390258.jpg`,
		logo: `/images/clients/rabobank-2.svg`,
		color: '#001090',
	},
	{
		client: 'ING',
		path: 'ing',
		image: `/images/cases/stock-photo-london-uk-january-th-the-homepage-of-the-official-website-for-the-ing-group-the-dutch-1013358685.jpg`,
		logo: `/images/clients/ing.png`,
		color: '#ee6f33',
		stack: [
			'Scala',
			'Finagle',
			'Cassandra',
			'Phantom DSL',
			'AngularJS',
			'Polymer',
		],
	},
	{
		client: 'SKG',
		path: 'skg',
		image: `/images/cases/banners-cropped-images-SKG_sfeerbeelden-adviesopmaat-0-326-1500-562-1485443956-df9f1ec873b883e8004d80f6aced3963.jpg`,
		logo: `/images/clients/skg.svg`,
		color: '#9D1535',
		stack: [
			'Play!',
			'Slick',
			'Akka',
			'Postgres',
			'Angular 2',
			'TypeScript',
			'Docker',
			'DCOS',
			'Circle CI',
		],
	},
	{
		client: 'Port of Roterdam',
		path: 'port-of-rotterdam',
		image: `/images/cases/stock-photo-large-container-vessel-unloaded-in-port-of-rotterdam-283990010.jpg`,
		logo: `/images/clients/port_of_rotterdam_dark.svg`,
		color: '#002d60',
		stack: [
			'Scala',
			'Play!',
			'Akka',
			'Akka Persistence',
			'Akka Streams',
			'RxScala',
			'Spark',
			'Slick',
			'Heroku',
			'React',
			'React native',
			'Typescript',
			'AWS',
			'AWS Dynamodb',
			'Elastic Beanstalk',
		],
	},
	{
		client: '42 Education',
		path: '42-education',
		image: `/images/cases/42education.jpg`,
		logo: `/images/clients/42_education.png`,
		color: '#222',
	},
	{
		client: 'Gracenote Sports',
		path: 'gracenote-sports',
		image: `/images/cases/stock-photo-pyeongchang-south-korea-february-olympic-champion-martin-fourcade-of-france-1029727372.jpg`,
		logo: `/images/clients/gracenote_dark.svg`,
		color: '#e31b23',
	},
];

export default casesList;
